version: '3.8'

services:
  postgres-db:
    image: postgres:14
    container_name: postgres-db
    environment:
      POSTGRES_USER: tg_user
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: tg_bot
    ports:
      - "5432:5432"

  avito-app:
    build: .
    container_name: BB_bot
    env_file:
      - .env
    ports:
      - "3001:3001"
    depends_on:
      - postgres-db
